
# All available settings of specific linters.
linters-settings:
  forbidigo:
    # Forbid the following identifiers (list of regexp).
    forbid:
      # Optionally put comments at the end of the regex, surrounded by `(# )?`
      # Escape any special characters.
      - 'fmt\.Print.*(# Do not commit print statements\.)?'
      - 'os\.Getenv.*(# Use config wrapper.)?'
    exclude_godoc_examples: false
  # gofmt:
    # Simplify code: gofmt with `-s` option.
    # Default: true
    # simplify: false
  # misspell:
  #   # Correct spellings using locale preferences for US or UK.
  #   # Setting locale to US will correct the British spelling of 'colour' to 'color'.
  #   # Default is to use a neutral variety of English.
  #   locale: US
  #   ignore-words:
  #     - someword
  # staticcheck:
  #   # Select the Go version to target.
  #   # Default: 1.13
  #   go: "1.15"
  #   # https://staticcheck.io/docs/options#checks
  #   checks: [ "all" ]
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  # Disable all linters.
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - forbidigo
    - gofmt
    - nolintlint


# issues:
#   exclude-rules:
#     - path: cmd/integration/integration_test.go
#       text: "`os.Getenv`"
#       linters:
#         - forbidigo
