FROM golang:1.17.9-bullseye

RUN apt-get update

RUN go install github.com/ashanbrown/forbidigo@v1.3.0
RUN go install honnef.co/go/tools/cmd/staticcheck@2022.1.1
RUN go install github.com/cosmtrek/air@v1.27.10

# WORKDIR /app

RUN apt update
RUN apt install -y apt-transport-https
RUN curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/gpg.2F8CB673971B5C9E.key' | apt-key add -
RUN curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/config.deb.txt?distro=debian&codename=any-version' > /etc/apt/sources.list.d/go-swagger-go-swagger.list
RUN apt update 
RUN apt install swagger

WORKDIR /go/src


ENTRYPOINT ["/bin/bash"]